# Generated by Django 4.2.7 on 2026-04-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('europe', 'Europe'), ('asia', 'Asia'), ('north_america', 'North America'), ('south_america', 'South America'), ('africa', 'Africa'), ('oceania', 'Oceania'), ('middle_east', 'Middle East')], default='asia', max_length=50)),
                ('short_description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('avg_temp_monthly', models.TextField(blank=True)),
                ('ideal_durations', models.TextField(blank=True)),
                ('budget_level', models.CharField(choices=[('Budget', 'Budget'), ('Mid-range', 'Mid-range'), ('Luxury', 'Luxury')], default='Mid-range', max_length=20)),
                ('culture', models.IntegerField(default=3)),
                ('adventure', models.IntegerField(default=3)),
                ('nature', models.IntegerField(default=3)),
                ('beaches', models.IntegerField(default=3)),
                ('nightlife', models.IntegerField(default=3)),
                ('cuisine', models.IntegerField(default=3)),
                ('wellness', models.IntegerField(default=3)),
                ('urban', models.IntegerField(default=3)),
                ('seclusion', models.IntegerField(default=3)),
                ('image_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('utility_type', models.CharField(choices=[('ATM', 'ATM'), ('Washroom', 'Washroom'), ('Hospital', 'Hospital'), ('Police', 'Police'), ('Hotel', 'Hotel')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField(blank=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='destinations.destination')),
            ],
        ),
    ]
